Traceback (most recent call last):
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
a = np.array([1, 2, -3, 4, -5])
npt.assert_equal(set_negative_to_zero(a), [1, 2, 0, 4, 0])
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m a [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m1[39m, [38;5;241m2[39m, [38;5;241m-[39m[38;5;241m3[39m, [38;5;241m4[39m, [38;5;241m-[39m[38;5;241m5[39m])
[0;32m----> 2[0m [43mnpt[49m[38;5;241;43m.[39;49m[43massert_equal[49m[43m([49m[43mset_negative_to_zero[49m[43m([49m[43ma[49m[43m)[49m[43m,[49m[43m [49m[43m[[49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[38;5;241;43m2[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[38;5;241;43m4[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m

File [0;32m~/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/numpy/testing/_private/utils.py:362[0m, in [0;36massert_equal[0;34m(actual, desired, err_msg, verbose)[0m
[1;32m    359[0m [38;5;28;01mtry[39;00m:
[1;32m    360[0m     [38;5;66;03m# Explicitly use __eq__ for comparison, gh-2552[39;00m
[1;32m    361[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m (desired [38;5;241m==[39m actual):
[0;32m--> 362[0m         [38;5;28;01mraise[39;00m [38;5;167;01mAssertionError[39;00m(msg)
[1;32m    364[0m [38;5;28;01mexcept[39;00m ([38;5;167;01mDeprecationWarning[39;00m, [38;5;167;01mFutureWarning[39;00m) [38;5;28;01mas[39;00m e:
[1;32m    365[0m     [38;5;66;03m# this handles the case when the two types are not even comparable[39;00m
[1;32m    366[0m     [38;5;28;01mif[39;00m [38;5;124m'[39m[38;5;124melementwise == comparison[39m[38;5;124m'[39m [38;5;129;01min[39;00m e[38;5;241m.[39margs[[38;5;241m0[39m]:

[0;31mAssertionError[0m: 
Items are not equal:
 ACTUAL: None
 DESIRED: [1, 2, 0, 4, 0]

