Traceback (most recent call last):
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/olav/.pyenv/versions/3.12.1/envs/bb1000/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Verify Vector3D constructor
from pytest import approx
vector = Vector3D(1.0, 2.0, 4.0)

assert vector.coord_x == approx(1), f'{vector.coord_x=} != 1'
assert vector.coord_y == approx(2), f'{vector.coord_y=} != 2'
assert vector.coord_z == approx(4), f'{vector.coord_z=} != 4'
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 3[0m
[1;32m      1[0m [38;5;66;03m# Verify Vector3D constructor[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpytest[39;00m [38;5;28;01mimport[39;00m approx
[0;32m----> 3[0m vector [38;5;241m=[39m [43mVector3D[49m[43m([49m[38;5;241;43m1.0[39;49m[43m,[49m[43m [49m[38;5;241;43m2.0[39;49m[43m,[49m[43m [49m[38;5;241;43m4.0[39;49m[43m)[49m
[1;32m      5[0m [38;5;28;01massert[39;00m vector[38;5;241m.[39mcoord_x [38;5;241m==[39m approx([38;5;241m1[39m), [38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mvector[38;5;241m.[39mcoord_x[38;5;132;01m=}[39;00m[38;5;124m != 1[39m[38;5;124m'[39m
[1;32m      6[0m [38;5;28;01massert[39;00m vector[38;5;241m.[39mcoord_y [38;5;241m==[39m approx([38;5;241m2[39m), [38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mvector[38;5;241m.[39mcoord_y[38;5;132;01m=}[39;00m[38;5;124m != 2[39m[38;5;124m'[39m

[0;31mTypeError[0m: Vector3D() takes no arguments

